apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-alerts
  namespace: monitoring
spec:
  route:
    receiver: 'discord'
    groupBy: ['alertname', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  receivers:
    - name: 'discord'
      discordConfigs:
        - apiURL:
            name: discord-webhook-url
            key: address
          sendResolved: true
