apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-namespace.yaml
  - observability.yaml
  - weave-gitops-dashboard.yaml
  - app-kustomization.yaml
  - postgres.yaml
  - alertmanager-config.yaml
  - sealed-discord-secret.yaml
  - sealed-db-secret.yaml
