---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    address: AgBP2Ke4uMUA7+qjFJHV0aNq9WDwWggj3Mk3lzFHAdrF09sUHjqxwhDfhd/yYBd40q0c42nT5st53YisusBpL802nPK3x2iUfaebPspObMc8UMuRRt6KuHpz4rwT30TaOv7op1ameC4diqDBTkXaDQo3KcnJ6sb3Sosb06iQcrzIJ75TJlvIpCOO6R+Udc/HrVNP5J5/nkxsJe8e0G8C1vzvDwpXugDakFZy+9KbDxfg1jCxv5Xc+evtgaRSW82YMcjz4mx6wFUQy72YlNekU56JDKC3vCDUmmkaQfJT9ilHmEQCfIz0dma5meCh6zVqbcB+gWlB9QpJtNoMUL4vlqJHMrfDiWiDD7VIDJ1lf5zgXuMf70TO09TVcqhVq6hy3qZ7XaTEF2aJsWIGxocb6eMK1sjvbWyES13WKTg8e6JR/gDonRmdeUIVoWReFQnTqv2xra9hIaksyriFICW4ZQ97HYpb08gQRJ3NPCJmG85iFSdgqQ8i5px2EdgJSJSuxtls9qj0svsB90kV7xA8PGitTuWPcqDUcPLVbSCFDKKVXPzBP/qyZN5e1Y7mlxxcrxUlgcF/u2K0T5XFbTS/CFZeLyXZoS0WHRXkMLwepV2fM0vV1rjRkLrFS284TKfQo9REfuzUY7uj98s8tabsX4oIcbs61n+Len1VV1L8wlmkiLGIYaC95/bW9RBY97cDi8mISDZzsS7jY0ASYKH3hFHHSCZW6NoCA92zU4cbuYdJ1L3+g7xFMPBjePWy4h1exudiYuoy5d5/HdFziMjBAt7oNQnWNrDZqMc7Zd2i9uoNGBKBTL1qrN0G0ChC1m3sOyp2xqGupfP6eYQyBPnl3YTiKAbffPmQYuGg
  template:
    metadata:
      name: discord-webhook-url
      namespace: monitoring
    type: Opaque
