---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    address: AgCudX+PLDuVYDilZn8g2/IwFyDECDPCJ6kSsLruzSvyHLbHkPHgEgt28WXEAMCsnGsY7I72FVa3n7+OuL9e+rHL25heNtKyDQ1SccKHFamXjm75Uqfq0NqXUzNIGXtByrXxZeuZ6nuHYRiPCeSxtT/bRCm2bZdJre2dGfvvSyINQwMEtnhVIYToOXW483dEu6QhH4OEmmeUCQoEn08bfKJVyccW8e+DtgCvhfiCDGpkXFY6l+1QDxJy8hxjdh3RSA2cku3LrXZ28dICIgbD2dARHY/Kpa6g+n9zYu1py1G1dT1SWCGsPYqaoT1DiDmVB7JrDRJpMcKWKrcbRMXsl+hTVEbm3d3FMHbZn8+yTgei3YazhL6Mz3VkX8nzw7FeCTakjY5qG9I05TCljG2+4PG/5qbKfl3z9I7JO+q5ZI/i2Iqqze1rv4dMUfcmkCsOaED7tpYFbGHMjoK1YPcTT+osLDgOoDfj+GD5uzS6ctkBNCquUZqRTyMInSwAPpT1WfLly45w7/fhzelNkyfSM42pHKKjIbJizVpSeevDI/q+CemCMR6L9IxAkPk6ds802jYlT7cfPP9yVPqhiUbZmeylEupUgiubRQ3GfTVOMi8eZ0pW+lbTGOuIGbDO6jwuVcp4Of6SG+thUBSoLCTc0xLHakkZMmG4B9ndxpW9p9uL4fGAs3h2tjFg7//h0X6U1tTXJ0Ov1pc7VNBM90J9Bdj1euhuP2Dey0Mb2KsMApPhzJjDF9/9iYwDSrZNoDaknqicQWznhLz5gG9fAch2Qmvs/SUk/apBRLUlgpF3YtRpRkqcaKDcyVKgrC7HJxBy7/SAgDcztMvvaBaGDTmMU46Vic8KxLFjMU/n
  template:
    metadata:
      name: discord-webhook-url
      namespace: monitoring
    type: Opaque
